id: I31496E16
legacy_id: P000587
ocr_import_info:
  bdrc_scan_id: W1KG4000
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T17:48:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:21:33.278710+00:00'
last_modified: 2022-08-31 23:21:40.865518
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4000
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4000
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཡག་རྒྱལ་གཏེར་སྟོན་བཟང་པོ་རྡོ་རྗེའི་གཏེར་བྱོན་སྲིན་རྒྱལ་བདུད་འདུལ་དྲག་པོའི་སྒྲུབ་ཐབས་ཡང་ཟབ་རྡོ་རྗེ་ཕ་ལམ་གྱི་ཆོས་སྡེ།
  author: བཟང་པོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5317396848306312
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1KG4070:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4070
      total_pages: 288
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4070.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5317396848306312
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
