id: opecha:P000587
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4000
  title: གཡག་རྒྱལ་གཏེར་སྟོན་བཟང་པོ་རྡོ་རྗེའི་གཏེར་བྱོན་སྲིན་རྒྱལ་བདུད་འདུལ་དྲག་པོའི་སྒྲུབ་ཐབས་ཡང་ཟབ་རྡོ་རྗེ་ཕ་ལམ་གྱི་ཆོས་སྡེ་
  volume: ''
  author: ''
