id: P000587
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4000
  title: གཡག་རྒྱལ་གཏེར་སྟོན་བཟང་པོ་རྡོ་རྗེའི་གཏེར་བྱོན་སྲིན་རྒྱལ་བདུད་འདུལ་དྲག་པོའི་སྒྲུབ་ཐབས་ཡང་ཟབ་རྡོ་རྗེ་ཕ་ལམ་གྱི་ཆོས་སྡེ་
  author: ''
  volumes:
    1154129e336a4583b73c4507b0a85534:
      image_group_id: I1KG4070
      title: Volume 1 of g.yag rgyal gter ston bzang po rdo rje'i gter byon srin rgyal
        bdud 'dul drag po'i sgrub thabs yang zab rdo rje pha lam gyi chos sde
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
